FROM node:20

WORKDIR /app
COPY frontend/package.json ./frontend/
RUN cd frontend && npm install
COPY frontend ./frontend
RUN cd frontend && npm run build
EXPOSE 5173
CMD ["sh", "-c", "cd frontend && npm run preview"]
