[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
select = ["E", "F", "B", "I"]
line-length = 88
src = ["backend"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
pythonpath = ["backend"]
