version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env
    volumes:
      - tekno_db:/app/tekno.db
      - ./service_account.json:/app/service_account.json:ro
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "5173:5173"

volumes:
  tekno_db:
