name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  backend:
    name: CI / backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      STEL_BASE_URL: ${{ secrets.STEL_BASE_URL }}
      STEL_API_KEY:  ${{ secrets.STEL_API_KEY }}
      SHEETS_SPREADSHEET_ID: ${{ secrets.SHEETS_SPREADSHEET_ID }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff==0.6.8 pytest

      - name: Ruff format (check only)
        run: ruff format --check .

      - name: Ruff lint
        run: ruff check .

      - name: Unit tests (mock)
        env:
          USE_STEL_MOCK: "true"
        run: pytest -q

      - name: Integration tests (STEL)
        if: ${{ env.STEL_BASE_URL != '' && env.STEL_API_KEY != '' }}
        env:
          USE_STEL_MOCK: "false"
        run: pytest -q

  frontend:
    name: CI / frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install deps (ci)
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build --if-present

  docker:
    name: CI / docker
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          push: false
          tags: backend:test

      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: frontend/Dockerfile
          push: false
          tags: frontend:test
