jobs:
  backend:
    name: CI / backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install ruff==0.6.8 black==24.8.0 pytest

      - name: Ruff (format check)
        run: ruff format --check backend

      - name: Ruff (lint)
        run: ruff check backend

      - name: Pytest (unit/mocks)
        env:
          USE_STEL_MOCK: "true"
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q
        working-directory: backend
